## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [0]:
import os
import numpy as np
import pandas as pd

In [0]:
# 設定 data_path
dir_data = './data/'

In [0]:
f_app = os.path.join(dir_data, '/content/application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: /content/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [0]:
print('row size:',app_train.shape[0], ', column size:', app_train.shape[1])

row size: 307511 , column size: 122

#### 列出所有欄位

In [0]:
print(app_train.columns.values.tolist())

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

#### 截取部分資料

In [0]:
print(app_train.head(1))

   SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0

[1 rows x 122 columns]

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [0]:
print(app_train.iloc[4])
print(app_train.iloc[2000:2005,0:8])

SK_ID_CURR                                           100007
TARGET                                                    0
NAME_CONTRACT_TYPE                               Cash loans
CODE_GENDER                                               M
FLAG_OWN_CAR                                              N
FLAG_OWN_REALTY                                           Y
CNT_CHILDREN                                              0
AMT_INCOME_TOTAL                                     121500
AMT_CREDIT                                           513000
AMT_ANNUITY                                         21865.5
AMT_GOODS_PRICE                                      513000
NAME_TYPE_SUITE                               Unaccompanied
NAME_INCOME_TYPE                                    Working
NAME_EDUCATION_TYPE           Secondary / secondary special
NAME_FAMILY_STATUS                     Single / not married
NAME_HOUSING_TYPE                         House / apartment
REGION_POPULATION_RELATIVE                         0.028663
DAYS_BIRTH                                           -19932
DAYS_EMPLOYED                                         -3038
DAYS_REGISTRATION                                     -4311
DAYS_ID_PUBLISH                                       -3458
OWN_CAR_AGE                                             NaN
FLAG_MOBIL                                                1
FLAG_EMP_PHONE                                            1
FLAG_WORK_PHONE                                           0
FLAG_CONT_MOBILE                                          1
FLAG_PHONE                                                0
FLAG_EMAIL                                                0
OCCUPATION_TYPE                                  Core staff
CNT_FAM_MEMBERS                                           1
                                          ...
DEF_30_CNT_SOCIAL_CIRCLE                                  0
OBS_60_CNT_SOCIAL_CIRCLE                                  0
DEF_60_CNT_SOCIAL_CIRCLE                                  0
DAYS_LAST_PHONE_CHANGE                                -1106
FLAG_DOCUMENT_2                                           0
FLAG_DOCUMENT_3                                           0
FLAG_DOCUMENT_4                                           0
FLAG_DOCUMENT_5                                           0
FLAG_DOCUMENT_6                                           0
FLAG_DOCUMENT_7                                           0
FLAG_DOCUMENT_8                                           1
FLAG_DOCUMENT_9                                           0
FLAG_DOCUMENT_10                                          0
FLAG_DOCUMENT_11                                          0
FLAG_DOCUMENT_12                                          0
FLAG_DOCUMENT_13                                          0
FLAG_DOCUMENT_14                                          0
FLAG_DOCUMENT_15                                          0
FLAG_DOCUMENT_16                                          0
FLAG_DOCUMENT_17                                          0
FLAG_DOCUMENT_18                                          0
FLAG_DOCUMENT_19                                          0
FLAG_DOCUMENT_20                                          0
FLAG_DOCUMENT_21                                          0
AMT_REQ_CREDIT_BUREAU_HOUR                                0
AMT_REQ_CREDIT_BUREAU_DAY                                 0
AMT_REQ_CREDIT_BUREAU_WEEK                                0
AMT_REQ_CREDIT_BUREAU_MON                                 0
AMT_REQ_CREDIT_BUREAU_QRT                                 0
AMT_REQ_CREDIT_BUREAU_YEAR                                0
Name: 4, Length: 122, dtype: object
      SK_ID_CURR  TARGET  ... CNT_CHILDREN AMT_INCOME_TOTAL
2000      102345       0  ...            0         225000.0
2001      102348       0  ...            0          54000.0
2002      102349       0  ...            1         234000.0
2003      102350       0  ...            0         247500.0
2004      102351       0  ...            0         297000.0

[5 rows x 8 columns]

In [0]:
print(app_train.loc[4])
print(app_train.loc[4, 'NAME_CONTRACT_TYPE'])

SK_ID_CURR                                           100007
TARGET                                                    0
NAME_CONTRACT_TYPE                               Cash loans
CODE_GENDER                                               M
FLAG_OWN_CAR                                              N
FLAG_OWN_REALTY                                           Y
CNT_CHILDREN                                              0
AMT_INCOME_TOTAL                                     121500
AMT_CREDIT                                           513000
AMT_ANNUITY                                         21865.5
AMT_GOODS_PRICE                                      513000
NAME_TYPE_SUITE                               Unaccompanied
NAME_INCOME_TYPE                                    Working
NAME_EDUCATION_TYPE           Secondary / secondary special
NAME_FAMILY_STATUS                     Single / not married
NAME_HOUSING_TYPE                         House / apartment
REGION_POPULATION_RELATIVE                         0.028663
DAYS_BIRTH                                           -19932
DAYS_EMPLOYED                                         -3038
DAYS_REGISTRATION                                     -4311
DAYS_ID_PUBLISH                                       -3458
OWN_CAR_AGE                                             NaN
FLAG_MOBIL                                                1
FLAG_EMP_PHONE                                            1
FLAG_WORK_PHONE                                           0
FLAG_CONT_MOBILE                                          1
FLAG_PHONE                                                0
FLAG_EMAIL                                                0
OCCUPATION_TYPE                                  Core staff
CNT_FAM_MEMBERS                                           1
                                          ...
DEF_30_CNT_SOCIAL_CIRCLE                                  0
OBS_60_CNT_SOCIAL_CIRCLE                                  0
DEF_60_CNT_SOCIAL_CIRCLE                                  0
DAYS_LAST_PHONE_CHANGE                                -1106
FLAG_DOCUMENT_2                                           0
FLAG_DOCUMENT_3                                           0
FLAG_DOCUMENT_4                                           0
FLAG_DOCUMENT_5                                           0
FLAG_DOCUMENT_6                                           0
FLAG_DOCUMENT_7                                           0
FLAG_DOCUMENT_8                                           1
FLAG_DOCUMENT_9                                           0
FLAG_DOCUMENT_10                                          0
FLAG_DOCUMENT_11                                          0
FLAG_DOCUMENT_12                                          0
FLAG_DOCUMENT_13                                          0
FLAG_DOCUMENT_14                                          0
FLAG_DOCUMENT_15                                          0
FLAG_DOCUMENT_16                                          0
FLAG_DOCUMENT_17                                          0
FLAG_DOCUMENT_18                                          0
FLAG_DOCUMENT_19                                          0
FLAG_DOCUMENT_20                                          0
FLAG_DOCUMENT_21                                          0
AMT_REQ_CREDIT_BUREAU_HOUR                                0
AMT_REQ_CREDIT_BUREAU_DAY                                 0
AMT_REQ_CREDIT_BUREAU_WEEK                                0
AMT_REQ_CREDIT_BUREAU_MON                                 0
AMT_REQ_CREDIT_BUREAU_QRT                                 0
AMT_REQ_CREDIT_BUREAU_YEAR                                0
Name: 4, Length: 122, dtype: object
Cash loans